### ISSUE TITLE
Změněné šablony

### ISSUE THREAD

**Issue by marekdedic** [golemsoftware/skautis-joomla#1]
Sablona protostar (Joomla 3.3.6) vůbec nemá složky určené k nahrazení.

**Comment by golemsoftware** [comment]
Pokud v dané šabloně nejsou obsaženy uvedené složky, pak jen nedojde k přepisu, pouze se nakopírují nové soubory.

Z hlediska struktury kódu šablon jsou ve složce šablony v "html" umístěny volitelné přepisy výchozích šablon komponent a modulů. Soubor v této komponentě skryje výchozí přihlašovací formulář a nahradí ho odkazem na skautIS login. Volitelně lze samozřejmě soubor jakkoliv upravit.
